// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK1XnxFcoYmD3IRt6aFBXYPm4b01mgkMQ',
    appId: '1:1048953934757:web:8f461235fcfe8224b84e4c',
    messagingSenderId: '1048953934757',
    projectId: 'fir-253c6',
    authDomain: 'fir-253c6.firebaseapp.com',
    storageBucket: 'fir-253c6.appspot.com',
    measurementId: 'G-JVGEFDXNN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHAKyvcvEahsyCQt-3jYSsiPA27npVds',
    appId: '1:1048953934757:android:0157bf3a4a54a2f6b84e4c',
    messagingSenderId: '1048953934757',
    projectId: 'fir-253c6',
    storageBucket: 'fir-253c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hRlHBFTrS2AHElfYyowzWTG5P5T40jI',
    appId: '1:1048953934757:ios:8b39d04d5d26d922b84e4c',
    messagingSenderId: '1048953934757',
    projectId: 'fir-253c6',
    storageBucket: 'fir-253c6.appspot.com',
    iosBundleId: 'com.example.myApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8hRlHBFTrS2AHElfYyowzWTG5P5T40jI',
    appId: '1:1048953934757:ios:8d5f76c4043974ebb84e4c',
    messagingSenderId: '1048953934757',
    projectId: 'fir-253c6',
    storageBucket: 'fir-253c6.appspot.com',
    iosBundleId: 'com.example.myApp2.RunnerTests',
  );
}
