// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlNjKxY_8zTRt_Qg-iMbnylF2ssDhNuQ',
    appId: '1:751666032118:web:c2c41bf0b686f9f8856bd7',
    messagingSenderId: '751666032118',
    projectId: 'fir-beb70',
    authDomain: 'fir-beb70.firebaseapp.com',
    storageBucket: 'fir-beb70.appspot.com',
    measurementId: 'G-H3L2RP5MBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJljwtzy9IzKvrwjq6RCof0YlTMdcbMA',
    appId: '1:751666032118:android:143ac65a3b5ff3cb856bd7',
    messagingSenderId: '751666032118',
    projectId: 'fir-beb70',
    storageBucket: 'fir-beb70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYydXW9op3syo2w7RX1chugbSgycS8Z4',
    appId: '1:751666032118:ios:11230a5308045604856bd7',
    messagingSenderId: '751666032118',
    projectId: 'fir-beb70',
    storageBucket: 'fir-beb70.appspot.com',
    iosBundleId: 'com.example.myApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOYydXW9op3syo2w7RX1chugbSgycS8Z4',
    appId: '1:751666032118:ios:90ba4e5a2c1629b0856bd7',
    messagingSenderId: '751666032118',
    projectId: 'fir-beb70',
    storageBucket: 'fir-beb70.appspot.com',
    iosBundleId: 'com.example.myApp2.RunnerTests',
  );
}
